---
ansible_host: cfrz4
ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
ansible_become: no

sssd_owner: root
sssd_group: wheel

sshd_service: sshd
sudo_admin_group: ldapwheel

sysconfdir: /usr/local/etc

# sshd_config
authorizedkeyscommand: /usr/local/bin/sss_ssh_authorizedkeys


