all:
  children:
    servers:
      hosts:
        noble:
        redhat:
        questing:
        xubuntu:
        parrot:
        cfrz4:
        rocky:
        trixie:
        jammy:
        bookworm:
        oracle:
        freebsd:
