- name: setup wayvnc
  hosts: questing
  
  #environment:
  #  http_proxy: http://proxy.example.com:8080
  #  https_proxy: http://proxy.example.com:8080

  roles:
  - name: sway
    tags: sway
    become: true

  - name: wayvnc
    tags: wayvnc
    become: true
  
  - name: user
    tags: user
    become: false
  
  - name: japanese
    tags: japanese
    become: false

