- name: setup wayvnc
  hosts: questing

  #environment:
  #  http_proxy: http://proxy.example.com:8080
  #  https_proxy: http://proxy.example.com:8080

  tasks:
  - name: apt update
    ansible.builtin.apt:
      update_cache: yes

  - name: install sway
    ansible.builtin.apt:
      name:
      - sway
      - sway-backgrounds
      - swayidle
      - alacritty
      - bemenu
      state: present
  
  - name: install wayvnc
    ansible.builtin.apt:
      name: wayvnc
      state: present

  - name: install sway@.service
    ansible.builtin.template:
      src: sway@.service
      dest: /usr/lib/systemd/system/

  - name: systemctl daemon-reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: restart gdm3
    ansible.builtin.systemd_service:
      name: gdm3
      state: restarted

  - name: copy custom.conf
    ansible.builtin.template:
      src: custom.conf
      dest: /etc/sway/config.d/

